# This file lets you run the example with a single command: docker-compose up
# Download docker here: https://www.docker.com/products/docker-desktop
#
# This docker compose starts two services:
# 1. a SQLPage service that serves a simple page with a login button
# 2. a Keycloak service that acts as an OpenID Connect provider (manages users and authentication)
#

services:
  sqlpage:
    image: lovasoa/sqlpage:main # Use the latest development version of SQLPage
    volumes:
      - .:/var/www
      - ./sqlpage:/etc/sqlpage
    environment:
      - OIDC_AUTHORIZATION_ENDPOINT=http://localhost:8181/realms/sqlpage_demo/protocol/openid-connect/auth
      - OIDC_TOKEN_ENDPOINT=http://localhost:8181/realms/sqlpage_demo/protocol/openid-connect/token
      - OIDC_USERINFO_ENDPOINT=http://localhost:8181/realms/sqlpage_demo/protocol/openid-connect/userinfo
      - OIDC_END_SESSION_ENDPOINT=http://localhost:8181/realms/sqlpage_demo/protocol/openid-connect/logout
      - OIDC_CLIENT_ID=sqlpage
      - OIDC_CLIENT_SECRET=qiawfnYrYzsmoaOZT28rRjPPRamfvrYr
      - RUST_LOG=sqlpage=debug
    network_mode: host

  keycloak:
    image: keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-configuration.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm --http-port 8181
    network_mode: host
  
  cas:
    build:
      context: .
      dockerfile: cas.dockerfile
    environment:
      - CAS_SERVER_NAME=http://localhost:8080
      - CAS_SERVER_HOSTNAME=localhost
      - CAS_ADMIN_USER=admin
      - CAS_ADMIN_PASS=admin
    network_mode: host


